package com.petcare.entity;

public enum NotificationType {
    APPOINTMENT_BOOKED,
    APPOINTMENT_APPROVED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_REMINDER,
    PRESCRIPTION_READY,
    DOCTOR_APPROVED,
    DOCTOR_REJECTED,
    SYSTEM_ANNOUNCEMENT
}
